### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by cvvspb** [react-native-community/rn-diff-purge#13]
Maybe I don't understand something...
I thought the tool would show the difference between two versions, but it just shows the same amount of changes between any two versions.
I don't get it, please explain what am I doing wrong?

0.34.1 -> 0.59.8
<img width="1093" alt="Screen 2019-05-17 19 00 58" src="https://user-images.githubusercontent.com/23339794/57941121-b7976e80-78d6-11e9-8fb8-2a323816cdf4.png">

0.59.7 -> 0.59.8
<img width="1180" alt="Screen 2019-05-17 19 01 32" src="https://user-images.githubusercontent.com/23339794/57941116-b5cdab00-78d6-11e9-9b4b-aa65ec179aa1.png">

**Comment by adkenyon** [comment]
It appears to be working for me:
- [0.34.1 -> 0.59.8](https://github.com/react-native-community/rn-diff-purge/compare/release/0.59.8..release/0.34.1)
- [0.59.7 -> 0.59.8](https://github.com/react-native-community/rn-diff-purge/compare/release/0.59.8..release/0.59.7)

**Comment by adkenyon** [comment]
I think you have the branches reversed in your screenshots

**Comment by cvvspb** [comment]
@adkenyon, thanks! I don't know how that happened

**Comment by pvinis** [comment]
@cvvspb out of curiosity, how did you arrive in the URL you did? typed it manually, or selected the branches or something?

I'm asking to know because the "correct" way is through the diff chooser or table, and if you didn't find it through these, then we need to make it more obvious/prominent.
Thank you.

**Comment by cvvspb** [comment]
@pvinis , sorry for delay, I've missed your question.
I don't remember exactly: it was either from some external or internal link
But you can just view your README.md - it shows reversed (broken) links with three dots:

RN diff PURGE

This repository exposes an untouched React Native app generated with the CLI react-native init RnDiffApp. Each new React Native release causes a new project to be created, removing the old one, and getting a diff between them. This way, the diff is always clean, always in sync with the changes of the init template.

A dedicated branch per release makes changes very easy to watch. For example:

https://github.com/react-native-community/rn-diff-purge/compare/release/0.28.0...release/0.29.0 (Change in Android template)
https://github.com/react-native-community/rn-diff-purge/compare/release/0.29.0...release/0.29.2 (no change)
https://github.com/react-native-community/rn-diff-purge/compare/release/0.30.0...release/0.31.0 (minor change in .flowconfig )

**Comment by pvinis** [comment]
Ah indeed. Leftover from the old way. I corrected it. Thanks.
