### ISSUE TITLE
0.59.6 upgrade error

### ISSUE THREAD

**Issue by M45ter** [react-native-community/rn-diff-purge#15]
# Bug

## Environment info

React native info output:
  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (4) x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
      Memory: 2.36 GB / 7.94 GB
    Binaries:
      Yarn: 1.13.0 - D:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - D:\Program Files\nodejs\npm.CMD

Library version: 0.59.6

## Steps To Reproduce

Describe what you expected to happen:

git init
git add .
git commit -m "upgrade RN"
react-native upgrade 0.59.8

## Reproducible sample code

react-native upgrade 0.59.8
info Fetching diff between v0.59.6 and v0.59.8...
error Failed to fetch diff for react-native@0.59.8. Maybe it's not released yet?
info For available releases to diff see: https://github.com/react-native-community/rn-diff-purge#version-changes

**Comment by pvinis** [comment]
The 0.59.6 release was removed, so try to change your package.json to 0.59.5 and upgrade to .8 again.

Sorry for that..
