### ISSUE TITLE
Exclude Podfile.lock

### ISSUE THREAD

**Issue by guhungry** [react-native-community/rn-diff-purge#18]
# Feature Request
`Podfile.lock` was include in the diff which should be exclude same as `yarn.lock` or `package-lock.json`

## Why it is needed
Lock file shouldn't be include in diff since it generate different each time project generate given that some library update dependencies or release new version.
![image](https://user-images.githubusercontent.com/4032276/59243772-ce15b900-8c3b-11e9-976c-cac6c59156ef.png)

## Possible implementation
Add `Podfile.lock` in `.gitignore` in `app-base` branch

**Comment by pvinis** [comment]
True. I will add it. I saw it was there, but I thought it might have been a mistake with the release.

**Comment by pvinis** [comment]
Fixed. Of course now the diff shows that change too, but it's fine.
