### ISSUE TITLE
Different comparison of GitHub

### ISSUE THREAD

**Issue by gabriel-silva** [react-native-community/rn-diff-purge#23]
Hi Guys, 
The website https://react-native-community.github.io/upgrade-helper/?from=0.59.9&to=0.60.3 is giving different comparisons of github https://github.com/react-native-community/rn-diff-purge/compare/release/0.59.9..release/0.60.3

**Comment by KryDos** [comment]
hi @gabriel-silva,
could you please point to the difference. I quickly checked and couldn't spot it.

**Comment by gabriel-silva** [comment]
hi @KryDos, for example, this part is missing:

if (enableHermes) {
      def hermesPath = "../../node_modules/hermesvm/android/";
      debugImplementation files(hermesPath + "hermes-debug.aar")
      releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
      implementation jscFlavor
    }

**Comment by KryDos** [comment]
thanks @gabriel-silva,
I see them both available on github and on community site. Are you sure you look at `app/build.gradle` instead of just `build.gradle`? 

`app/build.gradle` seems collapsed by default on community site though.

**Comment by gabriel-silva** [comment]
@KryDos, with version 0.60.4, now it appeared at others lines of code :) 
thanks for help!

**Comment by pvinis** [comment]
There were some funky diffs, sorry for that. Everything should be fixed since a few days ago.

Let us know if there is another problem again. We appreciate the feedback.
