### ISSUE TITLE
error Failed to fetch diff for react-native@0.60.5. Maybe it's not released yet?

### ISSUE THREAD

**Issue by gibo77** [react-native-community/rn-diff-purge#25]
# Bug

c:\Users\Gilb\WifiLight>react-native upgrade
info No version passed. Fetching latest...
info Fetching diff between v0.59.9 and v0.60.5...
**error** Failed to fetch diff for react-native@0.60.5. Maybe it's not released yet?
info For available releases to diff see: https://github.com/react-native-community/rn-diff-purge#version-changes

c:\Users\Gilbert\WifiLightDimmer>react-native upgrade 0.59.10
error Trying to upgrade from newer version "0.59.9" to older "0.59.10"

## Environment info

  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (4) x64 Intel(R) Core(TM) i5 CPU       M 430  @ 2.27GHz
      Memory: 3.77 GB / 7.80 GB
    Binaries:
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5791312

 "dependencies": {
    "@react-native-community/slider": "^1.1.3",
    "react": "16.8.3",
    "react-native": "0.59.9",
    "react-native-elements": "^1.1.0",
    "react-native-gesture-handler": "^1.3.0",
    "react-native-image-picker": "^1.0.2",
    "react-native-vector-icons": "^6.6.0",
    "react-navigation": "^3.11.0"

## Steps To Reproduce

1. c:\Users\Gilb\WifiLight>react-native upgrade
2. c:\Users\Gilb\WifiLight>react-native upgrade 0.60.5
...

**Comment by gibo77** [comment]
Update: I do not have yarn installed in my laptop. I think this is the culprit, but I was not able to test it since I already did manual upgrade.

**Comment by datvp09** [comment]
+1 to me 9/9/2019

**Comment by gibo77** [comment]
I have to close this issue guys. I was able to upgrade manually, using the "Show me how to upgrade!". It took me a couple of hours. It would be nice if you can copy the content easily, because the normal block and copy includes the number on the left. 
The dependencies I will leave that out of here. But the basic program at react-native init worked.
But whoever encounter this issue, let us know here if just because yarn is not installed.

**Comment by oaosman84** [comment]
I'm seeing the same thing, currently on 0.59.10 and trying to get to 0.60.5 and getting the same errors:
```
yarn run v1.17.3
$ /Users/XXX/Developer/mobile/node_modules/.bin/react-native upgrade
info No version passed. Fetching latest...
info Fetching diff between v0.59.10 and v0.60.5...
error Failed to fetch diff for react-native@0.60.5. Maybe it's not released yet?
info For available releases to diff see: https://github.com/react-native-community/rn-diff-purge#version-changes
✨  Done in 1.54s.
```

**Comment by thymikee** [comment]
Maybe you have connection issues, or are behind a vpn or something?

**Comment by pvinis** [comment]
otherwise, there's always this: https://react-native-community.github.io/upgrade-helper/?from=0.59.10&to=0.60.5

**Comment by xuan9230** [comment]
Failed to upgrade from 0.59.5 to 0.60.5
`react-native upgrade` shows:
```
info No version passed. Fetching latest...
info Fetching diff between v0.59.5 and v0.60.5...
error Failed to fetch diff for react-native@0.60.5. Maybe it's not released yet?
```

**Comment by thymikee** [comment]
@xuan9230 maybe it's a proxy. See: https://github.com/react-native-community/cli/issues/707 for details

**Comment by rendomnet** [comment]
react-native upgrade
info No version passed. Fetching latest...
info Fetching diff between v0.59.9 and v0.61.2...
error Failed to fetch diff for react-native@0.61.2. Maybe it's not released yet?
info For available releases to diff see: https://github.com/react-native-community/rn-diff-purge#version-changes

**Comment by pvinis** [comment]
@rendomnet you are using an old version of the cli. make sure you use the latest. also probably it will be easier for you to use the upgrade-helper, and do go to 60 before going to 61.

**Comment by pvinis** [comment]
@halabe15 did you try the comment right above yours?

**Comment by jamieallen59** [comment]
To reiterate what @pvinis said as I missed it on first reading too:

If you're on a version `<= 0.59.10` and want to go to e.g. `0.61`, you **need to upgrade to 0.60 first**, then  you can run the upgrader to get up to `0.61`.
