### ISSUE TITLE
React Native Version mismatch

### ISSUE THREAD

**Issue by sg-tbiswas** [react-native-community/rn-diff-purge#26]
When I update mine react native app from 0.55.4 to 0.59.2 as per the steps described. I git a run time error.

![image_2019_09_16T13_51_35_706Z](https://user-images.githubusercontent.com/51081413/65036794-e1869d80-d969-11e9-98a1-2afa3c0e696c.png)

**Comment by filipegl** [comment]
Did you try run `yarn`?

**Comment by pvinis** [comment]
You might need to clear the cache, try `yarn start --reset-cache`.
