### ISSUE TITLE
0.61.1 is incorrectly using react 16.8.1

### ISSUE THREAD

**Issue by matt-oakes** [react-native-community/rn-diff-purge#27]
You can see this in the diff here:

https://react-native-community.github.io/upgrade-helper/?from=0.61.0&to=0.61.1

There are no commits between RN 0.61.0 and 0.61.1 which downgrade React. This version is also below the one used in RN 0.60, so I think it must be a mistake.

**Comment by codler** [comment]
👍

**Comment by friederbluemle** [comment]
The same issue can be seen for `0.61.2`:

https://react-native-community.github.io/upgrade-helper/?from=0.61.1&to=0.61.2

Several dependencies appear to have been _downgraded_. This is not the case, as can easily be checked by `npx react-native init rn0612 --version 0.61.2`.

Any updates on this?

**Comment by levibuzolic** [comment]
It looks like there haven't been any tags pushed since `0.60.0` - https://github.com/react-native-community/rn-diff-purge/tags

**Comment by Bardiamist** [comment]
I want to trust `rn-diff-purge` but that caught in error three times.

**Comment by pvinis** [comment]
Fixed. Unfortunately this comes from the new react native cli, but using the old cli produces correct diffs. We are trying to fix the problem that causes this. Until that is fixed, we try to generate the diffs with it initially, and if it's wrong, we regenerate them using the old cli. Sorry for the inconvenience.

**Comment by pvinis** [comment]
Interestingly, I rerun the script using npx for the new cli, and it worked this time. 🤔
