### ISSUE TITLE
git apply command fails with and error

### ISSUE THREAD

**Issue by adkaushik** [react-native-community/rn-diff-purge#28]
# Question

I am upgrading react native from version 0.56.0 to 0.57.0. I did follow all the steps in `USAGE.md`.
But the last step `git apply upgrade-rn.patch --exclude=package.json -p 2 --3way` fails with the following error: 
`error: unrecognized input`.
 Is it an issue with my `upgrade-rn.patch` file ?

**Comment by pvinis** [comment]
I would recommend you to use https://react-native-community.github.io/upgrade-helper/?from=0.56.0&to=0.57.8 from now on.

The git apply way is problematic, I will probably remove this as an option.
