### ISSUE TITLE
Proposal: automate workflow with GitHub Actions

### ISSUE THREAD

**Issue by lucasbento** [react-native-community/rn-diff-purge#32]
### Introduction

This is a proposal to automate the workflow of generating _diffs_ (for `rn-diff-purge` and `upgrade-helper`) when creating new releases, work that's currently relying solely on @pvinis.

### The Core of It

This proposal is to automate all the manual process with GitHub Actions, here's how we can do it:

#### In `react-native` main repository

1. Add a small GitHub Action to the main `react-native` repo to trigger a [`dispatch_event`](https://developer.github.com/v3/activity/events/types/#repositorydispatchevent) on new tags to `@react-native-community/rn-diff-purge`, this should also carry over the tag version, example of this can be seen [here](https://github.com/react-native-community/rn-diff-purge/blob/master/actions/notifyNewRelease/index.js#L39-L43).

#### In `rn-diff-purge`

1. Get the version param from the dispatch event in a GitHub Action;
1. Create a branch (e.g. `0.62.0-rc.5`) and push it (should be done on top of the last release branch);
1. Create and checkout to a staging branch (e.g. `0.62.0-rc.5-staging`);
1. Do a `react-native init`/`@react-native-community/cli init` (pls halp);
1. Commit all the changes to staging branch and push it;
1. Create PR from staging branch (`0.62.0-rc.5-staging`) to _tag branch_ (`0.62.0-rc.5`);
1. This PR needs to be reviewed, approved and merged by a maintainer;
1. After the PR is merged the diff is automatically shown on `upgrade-helper` and used in the CLI.

**If any of the automatically-handled steps fail, create an issue on `rn-diff-purge` mentioning that the process failed and tag maintainers**.

### Pros

- We can double-check the diff before it hits `upgrade-helper`;
- Will run as soon as there's a new tag in `react-native` repository.

### Discussion points

- How to handle the `RELEASES` file in this scenario? updating it will require two PRs, perhaps having another GitHub action to see that a PR was a merged then update the file automatically? 🤔

**Comment by pvinis** [comment]
> 2. Create a branch (e.g. 0.62.0-rc.5) and push it (should be done on top of the last release branch);

I wouldn't put it on top of anything. Currently, all new branches are started from the `app-base` branch and they are all independent, I think we should keep it like that, so we can generate diffs from any to any release.

**Comment by kelset** [comment]
we could probably also take a look at this https://github.com/acoates-ms/rnw-diff

From @ngerleman's message:
> Just in case there is interest, we have a workflow to automatically run react-native-init and commit it to a branch in the style of the diff repo.

**Comment by pvinis** [comment]
Closing this. We have that and it's working.
