### ISSUE TITLE
Upgrade from 0.61.5 -> 0.62.0 causes git issues on new check out

### ISSUE THREAD

**Issue by stigi** [react-native-community/rn-diff-purge#35]
# Bug report

The [upgrade step from 0.61.5 to 0.62.0](https://react-native-community.github.io/upgrade-helper/?from=0.61.5&to=0.62.0) contains an invalid change to [`.gitattributes`](https://raw.githubusercontent.com/react-native-community/rn-diff-purge/release/0.62.0/.gitattributes) and I don't know how it ended up there in the first place.

Adding those changes to an existing git repository will cause a fresh checkout of it to result in a dirty repo with a modified file `android/gradlew.bat`.

## Summary

If I set up a vanilla `0.62.0` project it won't have those changes: `npx react-native init test --version 0.62.0`:
```
~ cat test/.gitattributes
*.pbxproj -text
```

## Environment info

- macOS Catalina `10.15.4 (19E287)`
- `git --version`: `git version 2.24.1 (Apple Git-126)`
- `npx --version`: `6.13.4`
- `npx react-native --version`: `4.8.0`

## Steps to reproduce

1. Create a new RN project with `npx react-native init test --version 0.62.0`
2. Apply the `.gitattributes` changes from https://raw.githubusercontent.com/react-native-community/rn-diff-purge/release/0.62.0/.gitattributes
3. Push the repo to GitHub
4. Clone the repo into a new place
5. Check the git status and observe invalid changes
```
~ git status --short
 M android/gradlew.bat
```

Describe what you expected to happen:

In step 5: No output, indicating a clean and freshly checked out repo.

## Reproducible sample code

You can also just check out my test repo here: `git@github.com:stigi/rn-diff-0.62.0-gitattributes.git`

**Comment by homburg** [comment]
@pvinis This i blocking `npx react-native upgrade` for me as well.

As I see it we could fix it in 2 ways:

1. rewrite the history/move tags in this repository to ignore/move `.gitattributes`
2. Add logic to handle the issue in https://github.com/react-native-community/cli/blob/master/packages/cli/src/commands/upgrade/upgrade.ts

Do you have any preference on a solution?

**Comment by pvinis** [comment]
I commented on it here https://github.com/react-native-community/upgrade-support/issues/71#issuecomment-706028431.

Since I don't use Windows for developing RN stuff, I am not too interested or too capable to fix this at this point. I tried to fix it and it caused problems for others.

I'm happy to help if I can, but yea, feel free to work on this in any way you think is best.

I would need to spend time to refamiliarize myself with the problem and for the next month I can't do that unfortunately, but I'm happy to chat about it and or see the problem or a video of it or whatever and suggest solutions. If you feel any of these two makes the most sense, do it 👍. The RN team and community are always welcoming new fixes in tooling! I know I love these :D

**Comment by homburg** [comment]
@pvinis Thank you for your reply.

As the git release refs are branches, it should be easy to fix with a number of pull requests.

**Comment by homburg** [comment]
@pvinis Do you have a reference for the original reason to add the `.gitattributes` file? It seems like something that should be fixed in the official react native template

**Comment by pvinis** [comment]
I would say it's https://github.com/facebook/react-native/pull/28274

**Comment by homburg** [comment]
Thanks @pvinis 

I actually think (have not tested) that the bat rule should be in a `template/_gitattributes` in facebook/react-native.

`gradlew.bat` is committed to the facebook/react-native with `crlf` line endings, but when I try to create a new project from the template on mac, I get `gradlew.bat` with `lf` line endings.  And as there's no `.gitattributes` in the new project (from the default template), the file would be converted to `lf` line endings anyway on staging/commit.

**Comment by pvinis** [comment]
sounds like that would fix things then. maybe this exact change can be made into a PR for the RN repo. add a template gitattr and fix the line endings, then things should work fine. we can remove the gitattr from rndiffpurge after that 👌. good investigation.
