### ISSUE TITLE
confusing alpha version changes with stable version.

### ISSUE THREAD

**Issue by vikrantnegi** [react-native-community/rn-diff-purge#4]
I've been trying to upgrade my react native projects before I knew about this package and it was a horrible experience. I was never able to upgrade my projects successfully, but this library solved it and now I'm able to upgrade from any version to the latest version.

Although I recently faced a problem where react native release alpha versions of 0.59 and then there was also the stable release of 0.58.5.

Before that, I used to manually check the file changes and apply them to the project but now since there was no direct way knowing the changed files from 0.58.4 to 0.58.5 as there were alpha versions in between them.

This created a lot of confusion while tracking the file changes between the stable releases.

Is there any way we can skip the alpha versions between the stable versions? or maybe I'm doing this all wrong.

Thanks.

**Comment by pvinis** [comment]
This will be very soon solved.

Two things you can do for now are:

- https://github.com/react-native-community/rn-diff-purge/compare/version/0.58.4...version/0.58.5 open this link. These are just git diffs, so you can just take the url of any of the links on the readme, and change them to your desired diff. tadaa 🎉

- Check https://github.com/pvinis/rn-diff-purge and https://github.com/pvinis/rn-diff-purge for now. I have a full table there to go from any version to any version. This will make it easier. I will push these changes soon to this repo right here, but there is a small thing that I'm waiting for some feedback from GitHub.

I hope these two solve your problem. Feel free to let me know what you think, and close the issue if this is solved. Thanks! :)

**Comment by vikrantnegi** [comment]
Cool. Didn't knew that you can change the versions in the URL and get the diffs.

And Congrats  🎊 on getting you repo added on react native community.  Great job.

**Comment by pvinis** [comment]
Thanks. I didn't add it yet even though 2-3 others had the same problem, because I will replace it with the table, which will make everything easier. Did you try it?

**Comment by vikrantnegi** [comment]
@pvinis Yeah. It is working.

**Comment by pvinis** [comment]
Awesome! Closing this then.

**Comment by pvinis** [comment]
https://pvinis.github.io/purge-web/ ;)

**Comment by vikrantnegi** [comment]
@pvinis Cool.
