### ISSUE TITLE
No conflicting files after `apply` fails

### ISSUE THREAD

**Issue by Esemesek** [react-native-community/rn-diff-purge#5]
After fail in applying `diff` to the repo, no conflicting files are dumped. I tried applying different patches, but none of them works. This situation happens only in some repositories, but I don't know what factor is causing the error. The repository is private, but I will try to make reproduction repository.

cc @thymikee @pvinis

**Comment by thymikee** [comment]
I just encountered this issue in second project. We need some git expert on that, once we have a repro.

**Comment by pvinis** [comment]
Also I think this should be in the rn-cli repo.
Yes, a simple repro would help a lot. :)

**Comment by thymikee** [comment]
Moved to CLI repo. Can be closed here.
