### ISSUE TITLE
0.65.1 -> 0.66.0 is react-native-codegen really should be removed?

### ISSUE THREAD

**Issue by svbutko** [react-native-community/rn-diff-purge#50]
Xcode throws an error if it's not there

**Comment by svbutko** [comment]
The same thing is in https://react-native-community.github.io/upgrade-helper/

**Comment by HugoGresse** [comment]
I think I've just spend 4 hours finding the issue. 
First, the explicit "Codegen missing" error was not displayed, I needed to dig into the `projects.pbxproj` to add log to a file
The, finding this issue, removing my package-lock.json, cleaning and rebuilding...

**Comment by HugoGresse** [comment]
This is very weird, the issue was still here even when removing package-lock... so I add to add it back to dev dep :/
