### ISSUE TITLE
Missing some versions

### ISSUE THREAD

**Issue by alois-beto** [react-native-community/rn-diff-purge#60]
Due to problem with android build react-native released lots of patch versions yesterday but only 2 out of 8 have been added in this repo:
- 0.70.5: ❌
- 0.69.7: ✅
- 0.68.5: ✅
- 0.67.5: ❌
- 0.66.5: ❌
- 0.65.3: ❌
- 0.64.4: ❌
- 0.63.5: ❌

**Comment by pvinis** [comment]
all here https://github.com/react-native-community/rn-diff-purge/blob/master/RELEASES. Ill close this, feel free to reopen if you see something missing.
