### ISSUE TITLE
Gemfile.lock removed in v67.5 diff but not found in core changes

### ISSUE THREAD

**Issue by grgr-dkrk** [react-native-community/rn-diff-purge#62]
According to https://github.com/react-native-community/rn-diff-purge/compare/release/0.67.4..release/0.67.5, `RnDiffApp/Gemfile.lock` has been removed.
But I didn't see that change in the Core diff https://github.com/facebook/react-native/compare/v0.67.4...v0.67.5.
Is it okay to delete Gemfile.lock?
Thanks.

**Comment by blakef** [comment]
I'm seeing it there:
![CleanShot 2024-02-01 at 10 28 46@2x](https://github.com/react-native-community/rn-diff-purge/assets/49578/ee059ce9-71e8-493f-9f28-87791fc8c895)
![CleanShot 2024-02-01 at 10 29 16@2x](https://github.com/react-native-community/rn-diff-purge/assets/49578/ca26b435-5057-49e9-8785-c7e51e4f52b6)
