### ISSUE TITLE
React Native upgrade helper website not responding

### ISSUE THREAD

**Issue by chauhan-saurabh** [react-native-community/rn-diff-purge#64]

**Comment by chauhan-saurabh** [comment]
<img width="1675" alt="Screenshot 2022-12-25 at 1 05 17 PM" src="https://user-images.githubusercontent.com/31333681/209460448-de60d6bf-c46a-4c04-8277-1596c8ff4cd1.png">

**Comment by sajorahasan** [comment]
same again
<img width="1347" alt="Screenshot 2023-07-12 at 2 56 49 PM" src="https://github.com/react-native-community/rn-diff-purge/assets/19198921/eb0804a8-be88-47d4-a3e1-0ad56ea923b8">

**Comment by blakef** [comment]
Looks like transient issue.  Can't reproduce atm.  Thanks for the feedback, and feel free to re-raise if this occurs again.
