### ISSUE TITLE
react-native upgrade and Upgrade-helper is NOT WORKING

### ISSUE THREAD

**Issue by Mr-Akhil** [react-native-community/rn-diff-purge#65]
![image](https://user-images.githubusercontent.com/55000469/212523569-5588f1a8-b0f3-4be1-9c02-16d3814d15bb.png)
![image](https://user-images.githubusercontent.com/55000469/212523602-4f1b33ef-850d-42eb-bbd2-6c028283f8d5.png)
![image](https://user-images.githubusercontent.com/55000469/212523619-2e38ce49-3ffc-4245-a9b9-e46e395730f7.png)

**Comment by akshay030123** [comment]
same here this upgrade helper is not working... 
could you suggest some another way to update the project??
