### ISSUE TITLE
Missing react-native v0.74.2 in upgrade helper due to "publish" job failure

### ISSUE THREAD

**Issue by vshkl** [react-native-community/rn-diff-purge#78]
### Problem

The [`0.74.2`](https://github.com/facebook/react-native/releases/tag/v0.74.2) versions of `react-native` was published 3 days ago, yet it is still missing in the upgrade helper:

![CleanShot 2024-06-07 at 15 09 43](https://github.com/react-native-community/rn-diff-purge/assets/7419173/216c2b8d-7dd6-4b51-90e2-d814d2e9641a)

The CLI does not see it to:
```sh
info No version passed. Fetching latest...
info Fetching diff between v0.74.1 and v0.74.2...
error Fetch request failed with status 404: 404: Not Found.
error Failed to fetch diff for react-native@0.74.2. Maybe it's not released yet?
info For available releases to diff see: https://github.com/react-native-community/rn-diff-purge#diff-table-full-table-here
```

The publishing job failed:
https://github.com/react-native-community/rn-diff-purge/actions/runs/9370754752

![CleanShot 2024-06-07 at 15 14 19](https://github.com/react-native-community/rn-diff-purge/assets/7419173/d1e92d74-526a-4c22-aba6-3105ececfeb2)

**Comment by cortinico** [comment]
Thanks for reporting. @pvinis will look into it soon

**Comment by pvinis** [comment]
Should be good now. https://react-native-community.github.io/upgrade-helper/?from=0.73.8&to=0.74.2

**Comment by EvertEt** [comment]
@pvinis Something similar seems to have happened for 0.72.15: https://github.com/react-native-community/rn-diff-purge/actions/runs/9484694455

**Comment by pvinis** [comment]
fixed again. im not sure whats breaking it, so i try different things. ill check on the next one again.
