### ISSUE TITLE
RN 0.76.5

### ISSUE THREAD

**Issue by joe-sam** [react-native-community/rn-diff-purge#86]
Seems to have generated the wrong version or tagged the wrong commit [Commit 3763965](https://github.com/react-native-community/rn-diff-purge/commit/37639655deeb5eee03e540ee10c1d829a706173c#diff-8ba189ef36bdd964d61e661b9486dcb94e1fc97ef9ae8f4d3747e2057cffe0ec)

Package.json shows react native version as 0.76.4 and not 0.76.5

**Comment by cortinico** [comment]
This should be fixed now:
https://react-native-community.github.io/upgrade-helper/?from=0.76.4&to=0.76.5
